// Code generated by protoc-gen-go. DO NOT EDIT.
// source: merger.proto

package merger

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	Conns                int64    `protobuf:"varint,1,opt,name=Conns,json=conns,proto3" json:"conns,omitempty"`
	Timeout              int64    `protobuf:"varint,2,opt,name=Timeout,json=timeout,proto3" json:"timeout,omitempty"`
	Endtime              int64    `protobuf:"varint,3,opt,name=Endtime,json=endtime,proto3" json:"endtime,omitempty"`
	Hostname             string   `protobuf:"bytes,4,opt,name=Hostname,json=hostname,proto3" json:"hostname,omitempty"`
	Origin               string   `protobuf:"bytes,5,opt,name=Origin,json=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c1fd482da7fe1f7, []int{0}
}

func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetConns() int64 {
	if m != nil {
		return m.Conns
	}
	return 0
}

func (m *Params) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Params) GetEndtime() int64 {
	if m != nil {
		return m.Endtime
	}
	return 0
}

func (m *Params) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Params) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

type Report struct {
	Info                 *Params   `protobuf:"bytes,1,opt,name=Info,json=info,proto3" json:"info,omitempty"`
	Clients              []*Client `protobuf:"bytes,2,rep,name=Clients,json=clients,proto3" json:"clients,omitempty"`
	Points               []*Tuple  `protobuf:"bytes,3,rep,name=Points,json=points,proto3" json:"points,omitempty"`
	Errors               []int64   `protobuf:"varint,4,rep,packed,name=Errors,json=errors,proto3" json:"errors,omitempty"`
	Timeouts             []int64   `protobuf:"varint,5,rep,packed,name=Timeouts,json=timeouts,proto3" json:"timeouts,omitempty"`
	ScriptData           []byte    `protobuf:"bytes,6,opt,name=ScriptData,json=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c1fd482da7fe1f7, []int{1}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetInfo() *Params {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Report) GetClients() []*Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

func (m *Report) GetPoints() []*Tuple {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *Report) GetErrors() []int64 {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *Report) GetTimeouts() []int64 {
	if m != nil {
		return m.Timeouts
	}
	return nil
}

func (m *Report) GetScriptData() []byte {
	if m != nil {
		return m.ScriptData
	}
	return nil
}

type Client struct {
	Id                   int64     `protobuf:"varint,1,opt,name=Id,json=id,proto3" json:"id,omitempty"`
	Origin               string    `protobuf:"bytes,2,opt,name=Origin,json=origin,proto3" json:"origin,omitempty"`
	Windows              []*Window `protobuf:"bytes,3,rep,name=Windows,json=windows,proto3" json:"windows"`
	Errors               []int64   `protobuf:"varint,4,rep,packed,name=Errors,json=errors,proto3" json:"errors"`
	Established          []int64   `protobuf:"varint,5,rep,packed,name=Established,json=established,proto3" json:"established"`
	Responses            int64     `protobuf:"varint,6,opt,name=Responses,json=responses,proto3" json:"responses,omitempty"`
	Timeouts             int64     `protobuf:"varint,7,opt,name=Timeouts,json=timeouts,proto3" json:"timeouts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c1fd482da7fe1f7, []int{2}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Client) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Client) GetWindows() []*Window {
	if m != nil {
		return m.Windows
	}
	return nil
}

func (m *Client) GetErrors() []int64 {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *Client) GetEstablished() []int64 {
	if m != nil {
		return m.Established
	}
	return nil
}

func (m *Client) GetResponses() int64 {
	if m != nil {
		return m.Responses
	}
	return 0
}

func (m *Client) GetTimeouts() int64 {
	if m != nil {
		return m.Timeouts
	}
	return 0
}

type Window struct {
	Value                int64    `protobuf:"varint,1,opt,name=Value,json=value,proto3" json:"value,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=Start,json=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,3,opt,name=End,json=end,proto3" json:"end,omitempty"`
	Iter                 int64    `protobuf:"varint,4,opt,name=Iter,json=iter,proto3" json:"iter,omitempty"`
	Count                int64    `protobuf:"varint,5,opt,name=Count,json=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Window) Reset()         { *m = Window{} }
func (m *Window) String() string { return proto.CompactTextString(m) }
func (*Window) ProtoMessage()    {}
func (*Window) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c1fd482da7fe1f7, []int{3}
}

func (m *Window) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Window.Unmarshal(m, b)
}
func (m *Window) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Window.Marshal(b, m, deterministic)
}
func (m *Window) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Window.Merge(m, src)
}
func (m *Window) XXX_Size() int {
	return xxx_messageInfo_Window.Size(m)
}
func (m *Window) XXX_DiscardUnknown() {
	xxx_messageInfo_Window.DiscardUnknown(m)
}

var xxx_messageInfo_Window proto.InternalMessageInfo

func (m *Window) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Window) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Window) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *Window) GetIter() int64 {
	if m != nil {
		return m.Iter
	}
	return 0
}

func (m *Window) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Tuple struct {
	Data                 []int64  `protobuf:"varint,1,rep,packed,name=Data,json=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tuple) Reset()         { *m = Tuple{} }
func (m *Tuple) String() string { return proto.CompactTextString(m) }
func (*Tuple) ProtoMessage()    {}
func (*Tuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c1fd482da7fe1f7, []int{4}
}

func (m *Tuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tuple.Unmarshal(m, b)
}
func (m *Tuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tuple.Marshal(b, m, deterministic)
}
func (m *Tuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tuple.Merge(m, src)
}
func (m *Tuple) XXX_Size() int {
	return xxx_messageInfo_Tuple.Size(m)
}
func (m *Tuple) XXX_DiscardUnknown() {
	xxx_messageInfo_Tuple.DiscardUnknown(m)
}

var xxx_messageInfo_Tuple proto.InternalMessageInfo

func (m *Tuple) GetData() []int64 {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "merger.Params")
	proto.RegisterType((*Report)(nil), "merger.Report")
	proto.RegisterType((*Client)(nil), "merger.Client")
	proto.RegisterType((*Window)(nil), "merger.Window")
	proto.RegisterType((*Tuple)(nil), "merger.Tuple")
}

func init() {
	proto.RegisterFile("merger.proto", fileDescriptor_4c1fd482da7fe1f7)
}

var fileDescriptor_4c1fd482da7fe1f7 = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x95, 0xb8, 0x4d, 0x5a, 0x77, 0xdb, 0xc1, 0x05, 0x96, 0x95, 0x7f, 0x55, 0x4e, 0x15,
	0xa0, 0x22, 0xfe, 0x48, 0x83, 0x49, 0xe3, 0xd0, 0x52, 0x41, 0x4f, 0x4c, 0xdd, 0x04, 0xe7, 0xac,
	0xf1, 0xba, 0xa0, 0xc6, 0x8e, 0x6c, 0x87, 0x89, 0x2b, 0xe2, 0xc2, 0x57, 0xe0, 0x00, 0xdf, 0x14,
	0x21, 0xfb, 0x75, 0x3a, 0xbb, 0x70, 0xd8, 0xa9, 0xf5, 0xf3, 0xfa, 0xf7, 0x5a, 0x7e, 0xde, 0xf8,
	0xc1, 0x3b, 0x25, 0x15, 0x2b, 0x2a, 0xc6, 0x95, 0xe0, 0x8a, 0x93, 0x08, 0x56, 0x83, 0xbe, 0xca,
	0x56, 0x2b, 0x2a, 0x9e, 0xc2, 0x0f, 0x14, 0xd3, 0xdf, 0x21, 0x8e, 0x4e, 0x32, 0x91, 0x95, 0x92,
	0x3c, 0xc3, 0xed, 0x29, 0x67, 0x4c, 0x26, 0xc1, 0x30, 0x18, 0xa1, 0xc9, 0xdd, 0x9f, 0xdf, 0x7f,
	0xa1, 0x3b, 0x9f, 0x25, 0x67, 0x47, 0xe9, 0x52, 0xeb, 0x4f, 0x78, 0x59, 0x28, 0x5a, 0x56, 0xea,
	0x6b, 0xba, 0x68, 0x1b, 0x85, 0x1c, 0xe2, 0xf8, 0xac, 0x28, 0x29, 0xaf, 0x55, 0x12, 0x1a, 0xe8,
	0xbe, 0x86, 0x12, 0x80, 0x14, 0x54, 0x5c, 0x2c, 0xb6, 0x9a, 0x06, 0x67, 0x2c, 0xd7, 0xab, 0x04,
	0xfd, 0x03, 0x52, 0xa8, 0x78, 0xa0, 0xd5, 0xc8, 0x11, 0xee, 0xbc, 0xe7, 0x52, 0xb1, 0xac, 0xa4,
	0x49, 0x6b, 0x18, 0x8c, 0xba, 0x93, 0x07, 0x9a, 0x3c, 0x00, 0xf2, 0xd2, 0x96, 0x5c, 0xb4, 0xd3,
	0x88, 0xe4, 0x25, 0x8e, 0x3e, 0x88, 0x62, 0x55, 0xb0, 0xa4, 0x6d, 0xc8, 0x7b, 0x9a, 0xdc, 0x07,
	0x92, 0x9b, 0x82, 0xcb, 0x45, 0x20, 0xa5, 0xdf, 0x10, 0x8e, 0x16, 0xb4, 0xe2, 0x42, 0x91, 0x37,
	0xb8, 0x35, 0x67, 0x17, 0xdc, 0x18, 0xd4, 0x7b, 0xbe, 0x37, 0xb6, 0x36, 0x83, 0x7f, 0x93, 0x81,
	0x6e, 0x77, 0x1b, 0xda, 0x15, 0xec, 0x82, 0xbb, 0xcd, 0x5a, 0x5a, 0x20, 0xef, 0x70, 0x3c, 0x5d,
	0x17, 0x94, 0x29, 0x99, 0x84, 0x43, 0xe4, 0xb6, 0x00, 0xd9, 0x73, 0x61, 0x09, 0x3b, 0x3d, 0x17,
	0xac, 0x46, 0xa6, 0x38, 0x3a, 0xe1, 0x85, 0xee, 0x83, 0x4c, 0x9f, 0xdd, 0xa6, 0xcf, 0x59, 0x5d,
	0xad, 0xa9, 0x77, 0xb1, 0xca, 0xec, 0xf3, 0x2e, 0x06, 0x92, 0xb6, 0x63, 0x26, 0x04, 0x17, 0x32,
	0x69, 0x0d, 0xd1, 0x08, 0x79, 0x14, 0x35, 0x05, 0x8f, 0x02, 0x49, 0x0f, 0xc0, 0x8e, 0x5c, 0x26,
	0x6d, 0xc3, 0xb9, 0x03, 0xb0, 0xf3, 0xf5, 0xc8, 0x4e, 0x23, 0x92, 0x57, 0x18, 0x9f, 0x2e, 0x45,
	0x51, 0xa9, 0xb7, 0x99, 0xca, 0x92, 0x68, 0x18, 0x8c, 0x76, 0xbc, 0x53, 0xa5, 0x29, 0x7a, 0xa7,
	0x82, 0x94, 0xfe, 0x40, 0x38, 0x02, 0x8f, 0xc8, 0x08, 0x87, 0xf3, 0xdc, 0x7e, 0xa3, 0x89, 0x86,
	0xfb, 0xd6, 0xf2, 0xdc, 0x05, 0xc3, 0x22, 0x77, 0xe6, 0x1d, 0xde, 0x7c, 0xde, 0xe4, 0x18, 0xc7,
	0x9f, 0x0a, 0x96, 0xf3, 0xab, 0xc6, 0xdc, 0xcd, 0x90, 0x40, 0x9e, 0xf4, 0x75, 0x9b, 0x3d, 0x68,
	0x73, 0x05, 0x3b, 0xd3, 0x45, 0x6c, 0xff, 0x91, 0x47, 0x5b, 0xae, 0x12, 0xbd, 0x7b, 0xd7, 0x75,
	0xf5, 0xda, 0xcb, 0xd7, 0xb8, 0x37, 0x93, 0x2a, 0x3b, 0x5f, 0x17, 0xf2, 0x92, 0xe6, 0xd6, 0xce,
	0x7d, 0x0d, 0x10, 0x0b, 0x5c, 0x57, 0xd3, 0x45, 0xcf, 0x59, 0x91, 0x63, 0xdc, 0x5d, 0x50, 0x59,
	0x71, 0x26, 0xa9, 0x34, 0x4e, 0xa2, 0xc9, 0x43, 0x0d, 0x0e, 0x00, 0x14, 0x4d, 0xcd, 0xbd, 0x61,
	0x77, 0xa3, 0x7a, 0x53, 0x8c, 0x0d, 0x7d, 0xe3, 0x29, 0xa6, 0x7f, 0x02, 0x1c, 0x81, 0x15, 0x3a,
	0x32, 0x3e, 0x66, 0xeb, 0x9a, 0xfe, 0x27, 0x32, 0xbe, 0x68, 0xdd, 0x8b, 0x0c, 0xa3, 0x68, 0xe4,
	0x54, 0x65, 0xa2, 0x09, 0x0c, 0x17, 0x91, 0x5a, 0xf7, 0x10, 0xa3, 0x90, 0xc7, 0x18, 0xcd, 0x58,
	0x6e, 0x83, 0xe2, 0x40, 0x03, 0xb7, 0x36, 0x41, 0xe1, 0x6e, 0x47, 0x94, 0xe5, 0x64, 0x8c, 0x5b,
	0x73, 0x45, 0x85, 0x09, 0x07, 0xe4, 0xbf, 0x49, 0x45, 0x85, 0xff, 0x26, 0x15, 0x15, 0x90, 0x7a,
	0x35, 0x53, 0x26, 0x13, 0xb6, 0x53, 0xaf, 0x66, 0x6a, 0x2b, 0xf5, 0x6a, 0xa6, 0xd2, 0x43, 0xdc,
	0x36, 0xef, 0x4c, 0x9f, 0x65, 0xbe, 0xe4, 0xc0, 0x0c, 0xce, 0x3d, 0x2b, 0xcf, 0x54, 0xe6, 0x9d,
	0xa5, 0x85, 0xf3, 0xc8, 0x64, 0xee, 0x8b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x4d, 0x86,
	0xa6, 0xa0, 0x05, 0x00, 0x00,
}
